name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  publish:
    name: "Publish release ${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Create draft release"
        uses: ./.github/actions/release
        with:
          type: production
          version: ${{ github.ref_name }}
          docker_username: ${{ secrets.DOCKERHUB_USER }}
          docker_password: ${{ secrets.DOCKERHUB_TOKEN }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}

