name: 'Test'
run-name: "Test PR ${{ github.event.pull_request.number }}"

on:
  pull_request:

# https://docs.docker.com/build/ci/github-actions/configure-builder/
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '<< go_version >>'

      - name: Test
        run: go test -v ./...